### ISSUE TITLE
a plugin that fix big imgs bugs or smth

### ISSUE THREAD

**Issue by Likver** [Aliucord/plugin-requests#1008]
### Plugin Description

So i noticed that when u tap on a img if its size is so big Aliucord doesn't load the img or even crash, so idk if its possible to fix this with a plugin but if it is, i would request a plugin that limits the resolution of an img when u enter to it, im not sure if the problem its 100% caused by the resolution but it also makes the pictures bigger on for example 1080p pics or more, i hope i did explain it well

### Request Agreement

- [X] I have made sure my plugin is possible and abides by the rules!

### ​

- [X] I did indeed check to make sure my plugin request is original!

**Comment by Likver** [comment]
An example of when the img doesn't load
![Screenshot_20220510-010510](https://user-images.githubusercontent.com/79934166/167512616-71778aec-47d8-4094-a72f-5e8f2628fd06.png)

**Comment by Likver** [comment]
Also, if i open the img by the browser btton it loads correctly

**Comment by Likver** [comment]
And this happens with some other pics
![Screenshot_20220510-010645](https://user-images.githubusercontent.com/79934166/167512803-91bc3046-5a9d-455f-b3f3-08836d2d9f2b.png)
It just crash

java.lang.RuntimeException: Canvas: trying to draw too large(119492800bytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
	at b.f.g.e.g.draw(ForwardingDrawable.java:2)
	at b.f.g.e.p.draw(ScaleTypeDrawable.java:7)
	at b.f.g.e.f.draw(FadeDrawable.java:27)
	at b.f.g.f.b.draw(RootDrawable.java:14)
	at android.widget.ImageView.onDraw(ImageView.java:1349)
	at com.facebook.samples.zoomable.ZoomableDraweeView.onDraw(ZoomableDraweeView.java:5)
	at android.view.View.draw(View.java:19315)
	at android.view.View.updateDisplayListIfDirty(View.java:18232)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4281)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4261)
	at android.view.View.updateDisplayListIfDirty(View.java:18181)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4281)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4261)
	at android.view.View.updateDisplayListIfDirty(View.java:18181)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4281)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4261)
	at android.view.View.updateDisplayListIfDirty(View.java:18181)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4281)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4261)
	at android.view.View.updateDisplayListIfDirty(View.java:18181)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4281)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4261)
	at android.view.View.updateDisplayListIfDirty(View.java:18181)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4281)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4261)
	at android.view.View.updateDisplayListIfDirty(View.java:18181)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:669)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:675)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:783)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3117)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2926)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2464)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1446)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7023)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:916)
	at android.view.Choreographer.doCallbacks(Choreographer.java:728)
	at android.view.Choreographer.doFrame(Choreographer.java:660)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:902)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:445)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by Likver** [comment]
Again idk if its fixable with a plugin that limitates the resolution of an img but i hope so

**Comment by Likver** [comment]
Ye it does but i think thats only in chat imgs

**Comment by Likver** [comment]
Okay fixed, that option in the zoom plugin was the problem, thx
